const mongoose = require('mongoose');
const alta = mongoose.model('alta',{
    No_Ticket:{ type: Number,
        required: true,}, 
        Se_Comunicó: { type: String,
            required: false,},
            No_Telefono:{ type: Number,
                required: false,}, 
                RFC: { type: String,
                    required: false,},
                    correo: { type: String,
                        required: false,},
                         Incidencia: { type: String,
                                 required: false,},
                                      detalle: { type: String,
                                          required: false,},
                                              observacion: { type: String,
                                                 required: false,},
                                                 detalleN2: { type: String,
                                                    required: false,},
                                                    observacionN2: { type: String,
                                                        required: false,},
                                                    fecha:{ type: String,
                                                        required: true,},
                                                        hora:{ type: String,
                                                            required: true,},
                                                            horaS:{ type: String,
                                                                required: false,},
                                                            Usuario:{ type: String,
                                                                    required: true,},
                                                                          Status:{ type: String,
                                                                              required: true,},
                                                                              Status_s:{ type: String,
                                                                                required: false,},
                                                                                comentario_S:{ type: String,
                                                                                    required: false,},
                                                                              Url:{ type: String,
                                                                                required: false,},
                                                                                Url_id:{ type: String,
                                                                                    required: false,}
})

module.exports = alta;
